spring:
  application.name:
    spring-boot-testing
  datasource:
    url: jdbc:postgresql://localhost:5432/testing
    username: sa
    password: password
  #  jpa:
  #    properties:
  #      hibernate.hbm2ddl.auto: jakarta. persistence.schema-generation.scripts.create-target
  flyway:
    create-schemas: true
    default-schema: test_schema

